import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-add-button-unit',
  templateUrl: './add-button-unit.component.html',
  styleUrls: ['./add-button-unit.component.scss']
})
export class AddButtonUnitComponent implements OnInit {
  title: string = "Hello World";

  getTitle(): string{
    return "This title was generated by a method"
  }

 ngOnInit(): void {
    //throw new Error('Method not implemented.');
    //this.title = "Now he is trying to change the title with ngOnInit"
    //alert("AddButtonUnitComponet initialized")
    setTimeout(()=>{
      this.title = "This is not the title you are looking for!"
    }, 3000)
  }

}
