import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-add-button-unit',
  templateUrl: './add-button-unit.component.html',
  styleUrls: ['./add-button-unit.component.scss']
})
export class AddButtonUnitComponent implements OnInit {
  title: string = "Hello World";
  ngOnInit(): void {


  }

  getTitle(): string {
    return "This title was generated by a method"
  }

  changeTitle(inputText): void {
    this.title = inputText;
  }
}
